### PR TITLE
Create Deploying Tanzu Kubernetes Grid Workload Cluster to Microsoft …

### PR DESCRIPTION
**Pull request by saintdle**
…Azure.md

### CODE REVIEW

**Comment by pescerosso** [comment]
Thanks I merged it. Let me know if you don't see it.

**Comment by saintdle** [comment]
> Thanks I merged it. Let me know if you don't see it.

Not seeing this post on the website at the moment.

**Comment by pescerosso** [comment]
I asked @afewell to look into it

**Comment by afewell** [comment]
@saintdle its visible now it looks like it was accidentally posted to the root directory instead of the blogs folder so I just moved it. 

Thanks!

**Comment by saintdle** [comment]
> @saintdle its visible now it looks like it was accidentally posted to the root directory instead of the blogs folder so I just moved it.
> 
> Thanks!

Ahh yes, I see that now, my mistake.

**Pull request merged**
