### PR TITLE
Create My CKA and CKAD journey blog

### PR DESCRIPTION
**Pull request by chutimaNan**
Please check out the blog. Thanks!

### CODE REVIEW

**Review by afewell — APPROVED** [review]
Thanks so much for sharing this @chutimaNan !!!

Just curious if you have seen our small CKA guide, if you happen to have any insights to add we would be grateful: https://modernapps.ninja/ckastudyguide_sg2378/docs/

Thanks!

**Comment by chutimaNan** [comment]
My pleasure! I will take a look at that site.
I would like to know how could I get a Hackathon Content Developer badge :)

**Comment by afewell** [comment]
Hi @chutimaNan I am finishing up the workflows that will automate provisioning the hackathon badges now and will have the instructions posted by tomorrow morning. The process will be that you will post an empty file to a particular directory and that will trigger the workflow to automatically provision your badge. I will send out an email and post to the members discussion board as soon as the workflows are ready, and I will also be reviewing on the ModernApps SRE Live call tomorrow and will post that video to the youtube page. Thanks!

**Comment by chutimaNan** [comment]
Thank you! Could you provide the link to the instruction page on how to submit a badge please? I cannot find the record on the youtube page yet.

**Pull request merged**
